// react-front/src/pages/cart.js
import React from 'react';
import { connect } from 'react-redux';
import { CartList } from '../components/cart/List';

const mapPropsToCartList = state => ({
    products: state.cart.products
});

const MappedCartList = connect(mapPropsToCartList)(CartList);

export const CartPage = () => {
    return (
        <div className="container mt-5">
            <h1 className="text-center">Cart</h1>
            <MappedCartList />
        </div>
    );
};

// front/pages/cart/index.vue
<template lang="pug">
  section.container.main.pt30
    h1.text-center.mb35 Cart
    product(v-for="product in products" :key="product.id" :product="product")
</template>

<script>
  import { mapState } from 'vuex'
  import Product from '@/components/cart/Product'

  export default {
    name: 'CartIndex',
    components: {
        Product
    },
    computed: {
      ...mapState({
        products: state => state.cart.products || []
      })
    },
  }
</script>
