// front/pages/index.vue
<template>
  <section class="container main pt30">
    <h1 class="text-center mb35">Catalog</h1>
    <pagination class="mb30" :last-page="lastPage" v-model="page" />
    <search class="mb30" />
    <products-list :columns="4" :products="products" />
  </section>
</template>

<script>
  import { mapState } from 'vuex'
  import ProductsList from '~/components/catalog/ProductsList'
  import Pagination from '~/components/catalog/Pagination'
  import Search from '~/components/catalog/Search'

  export default {
    async fetch ({ store }) {
      await store.dispatch("products/loadProducts", { count: 20, page: 1 })
    },
    name: 'pageIndex',
    components: {
      ProductsList,
      Pagination,
      Search,
    },
    data() {
      return {
        page: 1
      }
    },
    computed: {
      ...mapState({
        products: state => state.products.list || [],
        lastPage: state => state.products.lastPage || 0
      })
    },
    watch: {
      'page': function() {
        if (this.page > 0 && this.page <= this.lastPage)
          this.$router.push({name: 'page-page', params: { page: this.page }})
      }
    }
  }
</script>

// react-front/src/pages/index.js
import React, { useEffect } from 'react';
import { store } from '../store';
import { connect } from 'react-redux';
import { ProductsList } from '../components/product/List';
import { Pagination } from '../components/navigation/Pagination';
import { Search } from '../components/navigation/Search';
import { loadProducts, changeProductQuery } from '../actions';

const mapStateToProductProps = state => ({
    products: state.products.list
});

const ProductListComponent = connect(mapStateToProductProps)(ProductsList);

const mapStateToPaginationProps = state => ({
    lastPage: state.products.lastPage 
});

const PaginationComponent = connect(mapStateToPaginationProps)(Pagination);

export const HomePage = ({ match, history }) => {
    const changePageHandler = (page) => history.push(`/page/${page}`);

    const searchChangeHandler = ({ target: { value } }) => {
        store.dispatch(changeProductQuery({ name: value }));
        history.push('/page/1');
    };

    const currentPage = +match.params.page || 1;

    useEffect(() => {
        store.dispatch(loadProducts(currentPage, 20));
    });
    
    return (
        <div className="container mt-5">
            <PaginationComponent currentPage={ currentPage } changePage={changePageHandler} />
            <Search changeHandler={searchChangeHandler} />
            <ProductListComponent />
        </div>
    );
};
