// react-front/src/components/product/Detail.js
import React from 'react';

export const ProductDetail = ({ product }) => (
    <div className="product">
        <div className="row">
            <div className="col-md-4 col-sm-12">
                <img className="card-img-top" src={ product.img || '/images/no-product-img.png' } alt={ product.name } />
                <div className="text-center mt-2">
                    <button className="w-100 button button--primaty">Купить</button>
                    {
                        product.tags && product.tags.map(tag => 
                            <button className="button button--small button--primary-border tag mt-4" key={tag}>{ tag }</button>
                        )
                    }
                </div>
            </div>
            <div className="col-md-8 col-sm-12">
                <h2>{ product.name }</h2>
                <div className="asin">ASIN: { product.code }</div>
                <h3 className="field__title font-italic mt-5">Description</h3>
                <div className="field">{ product.description }</div>
                <h3 className="field__title font-italic mt-5">Specifications</h3>
                <div className="field">
                    {
                        product.specifications && product.specifications.map(spec => 
                            <div className="d-flex justify-content-between" key={spec.name}>
                                <span className="font-weight-bold">{ spec.name }</span>
                                <span>{ spec.value }</span>
                            </div>
                        )
                    }
                </div>
            </div>
        </div>
    </div>
);

// front/components/product/Detail.vue
<template lang="pug">
  .product
    .row
      .col-md-4.col-sm-12
        img.card-img-top(:src="product.img || '/images/no-product-img.png'" alt="product.name")
        .text-center.mt15
          .w-100.button.button--primary Купить
          button(v-for="tag in product.tags" :key="tag").button.button--small.button--primary-border.tag.mt35 {{ tag }}
      .col-md-8.col-sm-12
        h2 {{ product.name }}
        .asin ASIN: {{ product.code }}
        h3.mt40.field__title.pb5.font-italic
          | Description
        .field {{ product.description }}
        h3.mt40.field__title.pb5.font-italic
          | Specifications
        .field
          .field__spec.py10(v-for="spec in product.specifications" :key="spec.name")
            span.font-weight-bold {{ spec.name }}
            span {{ spec.value }}
</template>

<script>
  export default {
    name: 'ProductDetail',
    props: {
      product: {
        required: true,
        type: Object,
      }
    }
  }
</script>

<style lang="scss" scoped>
  @import "~assets/scss/vars";
  // colors
  $gray: map_get($colors, gray3);
  .tag + .tag {
    margin-left: 10px;
  }
  .field {
    &__title {
      border-bottom: 1px solid $gray;
    }
    &__spec {
      display: flex;
      justify-content: space-between;
    }
  }
  .w-100 {
    width: 100%;
  }
</style>
