// front/components/product/Card.vue
<template lang="pug">
  .card.mb20
    img.card-img-top.p10(:src="product.img || '/images/no-product-img.png'" alt="product.name")
    .card-body
      h5.card-title {{ product.name }}
    .card-body.btns
      .button.button--primary Подробнее
      .button.button--primary Купить
</template>

<script>
  export default {
    name: 'ProductCard',
    props: {
      product: {
        required: true,
      }
    }
  }
</script>

<style lang="scss" scoped>
  @import "~assets/scss/vars";
  // colors
  $white: map_get($colors, white);

  .card-body {
    background-color: $white;
  }
  .btns {
    display: flex;
    justify-content: space-between;
  }
  .button {
    width: 45%;
  }
</style>

// react-front/src/components/product/Card.js
import React from 'react';
import "./Card.css"

export const ProductCard = ({product}) => (
    <div className="card">
        <img class="card-img-top" src={product.img || '/images/no-product-img.png'} alt={product.name} />
        <div class="card-body">
        <h5 class="card-title">{ product.name }</h5>
        <h4>{ product.price }</h4>
        </div>
        <div class="card-body btns">
        <a class="button button--primary">More</a>
        <div class="button button--primary">Buy</div>
        </div>
    </div>
);
