// front/components/catalog/Search.vue
<template lang="pug">
  nav
    form.form-inline
      input.form-control(type="search" placeholder="Search" aria-label="Search" @keyup.enter="search" v-model="productName")
      button.button.button--primary(type="submit" @click="search") Search
</template>

<script>
  export default {
    name: 'CatalogSearch',
    computed: {
      productName() {
        return this.$store.state.products.query.name
      },
    },
    methods: {
      search() {

      }
    },
  }
</script>

<style lang="scss" scoped>
  .form-inline {
    justify-content: flex-end;
  }
</style>

// react-front/src/components/navigation/Search.js
import React from 'react';

export const Search = ({ changeHandler, placeholder }) => (
    <nav>
        <div className="form-inline justify-content-end mb-4">
            <input className="form-control" type="search" placeholder={placeholder || 'Search'} aria-label="Search" onChange={changeHandler} />
        </div>
    </nav>
);
